### ISSUE TITLE
Target="_blank" in drive folder links

### ISSUE THREAD

**Issue by edwinhamers** [woodwardtw/gfolder_embed#4]
When i click any folder link in the embedded iframe it will always redirect to a new tab and google drive. Any way around that ?

See html code 

![image](https://user-images.githubusercontent.com/3518216/81112482-fe82d780-8f1e-11ea-9ae9-da891531383d.png)

**Comment by woodwardtw** [comment]
I don't think there's going to be any easy way around this because it's [how Google Drive does things](https://support.google.com/drive/thread/24397145?hl=en). I couldn't find any url parameters in any documentation and I guessed at a few as well. 

If you really wanted to do it, you could write your own little app to serve up folders similar to what is describe on[ this StackOverflow response. ](https://stackoverflow.com/a/61034751/3390935)

**Comment by myosotisgit** [comment]
I was already afraid this is an internal thing.
Maybe with use of JQuery we could remove this specific "target" ... ??

**Comment by woodwardtw** [comment]
I'm afraid that leads you into XSS scripting issues. You can't go across domains with javascript without control of both ends and even then things get complicated.

**Comment by myosotisgit** [comment]
> I'm afraid that leads you into XSS scripting issues. You can't go across domains with javascript without control of both ends and even then things get complicated.

Good to know :-) 
As it is a totally diff. domain within the iframe that would be a security issue if that would be possible.. Allright. Giving that one up :-)
